node_js:
- '1'
- '2'
language: node_js
script: npm run test-ci
before_install:
- sudo apt-get -y update
- sudo apt-get install cimg-dev libphash0-dev libmagickcore-dev libwebp-dev libjpeg-dev
  libpng-dev libtiff-dev libgif-dev
- curl -s https://raw.githubusercontent.com/lovell/sharp/master/preinstall.sh | sudo
  bash -
- curl http://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz
  | sudo tar -C /usr/local/bin/ -xJ --strip-components=1
- mkdir ImageMagick
- curl http://www.imagemagick.org/download/ImageMagick.tar.gz | tar -C ImageMagick
  --strip-components=1 -xvz
- cd ImageMagick
- "./configure --with-webp=yes"
- make
- sudo make install
- sudo ldconfig /usr/local/lib
- cd ..
after_script: npm install coveralls@2 && cat ./coverage/lcov.info | coveralls
env:
  global:
  - secure: BQXOJg/uKRjgMovpTWgrIMijdJ5qsGlm+pZaOPocieqMLurCoFIYgkOF9dVgdKHAxcsCjG7ZzlOFL+CTE+3CrgIUkvAEjNgStt4zdOG91jE4pEQ5DJe1gugPoBgLM5y6jRjBU/Hcq1FtxQnwYAgDPXpJImCMpLufL71UyArWrBs=
  - secure: ANCnNxNzkTvX+u8Cxao3zsLwSwut0/WED7VAt4h6tjZ/3uVdP5KFv+s7jTNFepkqtEssStaXFJ4RyfL9LVJvvIf+U0VSkr4Hw60e6bx1/7WVTepA5imvy3OC2KN8BCmY++yzG4gjULj/BfqemmUPzFz0PhEnFpdSvmaztv5EjYg=
  - secure: d0TluIIRF7lw1U9Qz2rmJ+S8X9UBm6Khnf1KOeVuLCSvjcPtFbU8z4Ak0GYK9IJp5fF21xk7yg/HcXeX5vnOe8t3jaK9tPaCRBKIngZllwxJ7ZymozGPjk+AzAipAq1f68qqP9ifLNDC1Sx/+jWdlR2j7/LeYzdtBEDxFZbv2LU=
